name: 编译OpenWrt固件
on:
  workflow_dispatch:

#  schedule:
#    - cron: 0 8 */5 * *

jobs:
  update_external_airflow_fork:
    runs-on: ubuntu-latest
    steps:
      - uses: TobKed/github-forks-sync-action@master
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          upstream_repository: apache/airflow
          upstream_branch: master
          target_repository: danshui-git/op
          target_branch: main
          force: true
          tags: true
